config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/create'

  get 'users/new'

  get 'users/destroy'

  get 'users/show'

  devise_for :users
  
  resources :users

  devise_scope :user do
    authenticated :user do
      root to: "users#show", as: :authenticated_root, via: :get
    end
    
    unauthenticated do
      root to: "devise/sessions#new"
    end

  end
  
  resources :programs

  
  resources :quizzes
  get '' => "devise/sessions#new"
  

  

  

  
  get 'faq' => "pages#faq"

  get 'about' => "pages#about_us"

  get 'contact' => "pages#contact"

  get 'programs' => "pages#programs"
 
  get 'home' => "pages#home"
 
  get 'quizzes' => "quizzes#new"
  

  
  get 'profile' => "users#show"

end

app/models/program.rb
class Program < ActiveRecord::Base
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :quiz
end

app/models/user_favorite.rb
class UserFavorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :program
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def faq
  end

  def about_us
  end

  def contact
  end

  def home
  end

  def testimonials
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :description, :link, :price, :location_type, :city, :state, :grade_min, :grade_max, :subject, :gender, :ethnicity, :begin_date, :end_date, :travel, :age_min, :age_max)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @programs = Program.all
    @quiz = current_user.quiz
    
    @programs = @programs.where(subject:@quiz.interest) if @quiz.interest
    @programs = @programs.where(location_type:@quiz.travel_type) if @quiz.travel_type
    @programs = @programs.where(travel:@quiz.location_type) if @quiz.location_type
    #@programs = @programs.where(ethnicity:@quiz.ethnicity) if @quiz.ethnicity
    #@programs = @programs.where(price:@quiz.max_price) if @quiz.max_price
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = current_user.build_quiz(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id]) 
    end

    #Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params

      params.require(:quiz).permit(:location_type, :max_price, :ethnicity, :gender, :environment, :climate, :start_date, :end_date, :interest, :travel_type, :grade, :age, :user_id).delete_if{|k,v| v.blank?}
    end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
  end

  def create
  end

  def new
  end

  def destroy
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>

<%= yield %>

</body>
</html>

app/views/pages/about_us.html.erb
<div class = "container">
  <div class ="row">
    <div class ="col-xs-12 col-sm-12 col-md-12">
      <h1> What is Summer Enrichment? </h1>
      <h3> The Team </h3>
      <p> Our team is comprised of four high school students who have each struggled through the summers to find something interesting to do.  This website was designed to make finding a summer program easy and enjoyable.  We have also made it much easier for you as a student or parent to keep track of deadlines with our personalized favorites page.  This page will allow you to keep track of all of your deadlines for applications along with the ability to prioritize certain programs based off your personal needs.  We hope you find this convenient and helpful throughout your summer college endeavors. </p>
      
      <div class="media">
        <div class="pull-left">
        <a href ="#" >
            <img id="imgpeople" class="media-object" src="https://scontent.xx.fbcdn.net/hphotos-xat1/v/t1.0-9/11329985_938075132880377_7383813401737250237_n.jpg?oh=e1be097141a401cd1131c80fdbac98d6&oe=5617EA47" alt="arber">
          </a>
        </div>
        <div class="media-body">
          <h2 class="media-heading">Jamarber Bakalli</h2>
          <p>Head coder of Summer Enrichment, Jamarber "Arber" Bakalli learned to challenge himself throughout his MITES experience. He didn't think coding was for him, but he learned the basics and was able to craft the machinery behind Summer Enrichment. He currently lives in Staten Island, New York and hopes to study theoretical physics. </p>
          <p> Fun fact: Arber can make himself laugh. </p>
          <p> Summer programs attended: Blue Stamp Engineering 2014, Minority Introduction to Engineering and Science at MIT 2015.</p>
        </div>
      </div>
      
      <div class="media">
        <div class="pull-right">
        <a href ="https://twitter.com/brightoes" >
            <img id="imgpeople" class="media-object" src="https://scontent.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/10924765_958404550846817_2189375123591690497_n.jpg?oh=2d7cbeed185b995076afb2af99d35ea8&oe=5618FE83" alt="steph">
          </a>
        </div>
        <div class="media-body">
          <h2 class="media-heading">Stephanie Brito</h2>
          <p>As designer of Summer Enrichment, Stephanie Brito created all the aesthetic details of the site. She likes writing and doing other cool stuff in Miami, Florida, where she currently lives. She hopes to combine her love for journalism and molecular biology in a career that combines both fields. </p>
          <p>Fun fact: Stephanie can figure skate and used to play soccer, but was awful at it.</p>
          <p> Summer programs attended: JSA Summer School at Princeton 2013, Summer Academy for Math and Science 2014, Minority Introduction to Engineering and Science at MIT 2015.</p>
        </div>
      </div>
      
      <div class="media">
        <div class="pull-left">
        <a href ="#" >
            <img id="imgpeople" class="media-object" src="https://scontent-lga1-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/11050666_985449144809024_5251613205273949028_n.jpg?oh=e47143cadca7f666a38444b07af8d923&oe=56526616" alt="alex">
          </a>
        </div>
        <div class="media-body">
          <h2 class="media-heading">Alexander Iyabor</h2>
          <p>Alexander "Alex" Iyaber lead the Summer Enrichment team by not only managing, but also by working in the different departments. He currently lives in Atlanta, Georgia. He plans to study electrical engineering and computer science and business.</p>
          <p> Fun fact: Alex has played the violin for 5 years. </p>
          <p> Summer programs attended: Minority Introduction to Engineering and Science at MIT 2015.</p>
        </div>
      </div>
      
      <div class="media">
        <div class="pull-right">
        <a href ="#" >
            <img id="imgpeople" class="media-object" src="https://scontent.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11015800_984961594857779_8768801454159707063_n.jpg?oh=9a42ad8a2fc5b06b33aec811e8835ceb&oe=5616B4C6" alt="boris">
          </a>
        </div>
        <div class="media-body">
          <h2 class="media-heading">Boris Ragula</h2>
          <p>Coder and designer, Boris Ragula worked hard to learn about different concepts of coding. He currently lives in Gulfport, Mississippi, but wants to grow out of his roots to study theoretical physics.</p>
          <p> Fun fact: Boris has played classical piano for 12 years. </p>
          <p> Summer programs attended: Summer Institute for the Gifted at Emory 2013, iD Tech Intro to Programming 101 University of Texas in Austin 2014, Minority Introduction to Engineering and Science at MIT 2015.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class = "container">
  <div class ="row">
    <div class ="col-xs-12 col-sm-12 col-md-12">
      <h1> Contact </h1>
      <h4> Want to add your program to our site?</h4>
      <p> Email summer.enrichment@gmail.com with the environment, price, ethnicity, dates, travel type, grade level, and description of your summer program.</p>
      <h4> Technical Problems </h4>
      <p> Phone: (305)-123-4567</p>
      <h4> Administration</h4>
      <h5>Arber Bakalli </h5>
<p>Phone (347)-285-4405</p>
<p>Email: jamarberbakalli@gmail.com </p>

<h5> Stephanie Brito: </h5>
<p>Phone (786)-715-9942 </p>
<p>Email: stephanie.brito77@gmail.com</p>


<h5>Alex Iyabor </h5>
<p> Phone (678)-826-8574 </p>
<p>Email: alexiy101@gmail.com </p>

<h5> Boris Ragula: </h5>
<p>Phone (228)-243-2717 </p>
<p> Email: boris.ragula98@gmail.com </p>
    </div>
  </div>
</div>
  </body>
</html>

app/views/pages/faq.html.erb
<div class = "container">
  <div class ="row">
    <div class ="col-xs-12 col-sm-12 col-md-12">
      <h1> Frenquently Asked Questions </h1>
      <h4> How does the quiz work? </h4>
      <p> An algorithm created by our head coder, Arber, matches .</p>
    </div>
  </div>
</div>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-xs-12 col-sm-12 col-md-9" id="f">
      <!-- <h3> <a href = "#"> Column 1 </a> </h3> -->
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="http://mccortmirror.org/wp-content/uploads/2014/09/MIT-Campus.jpg" alt="MITES">
      <div class="carousel-caption">
        <h3>MITES @ MIT</h3>
        <p>A six-week immersion into engineering and science.</p>
      </div>
    </div>

    <div class="item">
      <img src="http://pics4.city-data.com/cpicc/cfiles8050.jpg" alt="LEDA">
      <div class="carousel-caption">
        <h3>LEDA</h3>
        <p text-color="red">A summer college prep program at Princeton.</p>
      </div>
    </div>

    <div class="item">
      <img src="http://blog.jasonoutlaw.com/wp-content/uploads/2012/12/2011-11-24-11.18.32-800x600.jpg" alt="Harvard">
      <div class="carousel-caption">
        <h3>Harvard</h3>
        <p>Summer programs at one of the top universities in the world.</p>
      </div>
    </div>

    <div class="item">
      <img src="http://www.ipwatchdog.com/wp-content/uploads/2015/02/Stanford.jpg
" alt="Stanford">
      <div class="carousel-caption">
        <h3>Stanford</h3>
        <p>JSA Summer School at Stanford.</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  
</div>
      
        <div class ="col-xs-12 col-sm-12 col-md-4">
          <!--<h4> <a href = "#"> Subcolumn 1 </a> </h4>-->
    

          <!-- Subcolumn 1 -->
          <h4>Social Media</h4>
          <a href="https://www.facebook.com/pages/Summer-Enrichment/384725751713291?skip_nax_wizard=true" class="btn-lg btn-social-icon btn-facebook" id="button">
    <i class="fa fa-facebook"></i> 
  </a> 
          <a href="https://twitter.com/summerenriched" class="btn-lg btn-social-icon btn-twitter" id="button">
    <i class="fa fa-twitter"></i> 
  </a> 
  <a href="https://instagram.com/summerenrichment/" class="btn-lg btn-social-icon btn-instagram" id = "button">
    <i class="fa fa-instagram"></i> 
  </a> 
  <a class="btn-lg btn-social-icon btn-youtube" id="button">
    <i class="fa fa-youtube"></i> 
  </a>
 <a class="twitter-timeline" href="https://twitter.com/summerenriched" data-widget-id="621840294980517888">Tweets by @summerenriched</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
</a>
 
    
        <div class = "col-xs-12 col-sm-12 col-md-8"> 
          <h4> The Team</h4>
          <div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" id="imgfour" src="https://scontent.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/11541978_985829271437678_546052331841267165_n.jpg?oh=6726b93eeb20cbaeba7c58f87fb3fdef&oe=5619FCD4" alt="The Group">
    </a>
  </div>
  <div class="media-body">
  </div>
</div>
<p style="color: white">.</p>
  <p>Summer Enrichment is an interactive tool specifically designed to help rising sophomores, juniors, and seniors find summer programs that they are compatible with. Throughout each of our individual experiences, each member of the team has experienced some difficulty in finding summer enrichment opportunities, and our mutual struggle brought us together at our very own first summer program that we attended together, The Minority Introduction to Engineering and Science. We are committed to establishing a useful tool that will consolidate readily available information on summer programs through the use of our online quiz, which will match environmental preferences and student situation with compatible summer programs. Our hope is that students can use our quiz and the resources we have made available to find a program that fits their needs. 
</p>
      
        </div>
</div>
    <div class = "col-xs-12 col-sm-12 col-md-3" id="f">
      <!--<h3> <a href = "#"> Column 2 </a> </h3>-->
    <table>
      <h1> Take the quiz</h1>

    <h3> <a href="quizzes/new">Click here: Find your perfect summer!</a></h3>
    </table>
      <h1> Testimonials</h1>
      <div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" id="imgtest" src="http://midchesh.ac.uk/files/images/Catherine%20Broadhurst%20Science.jpg" alt="Test">
    </a>
  </div>
  <div class="media-body">
  </div>
</div>
<h4> "This website made my time as a student much easier to find a summer program that suited my needs." - Stephanie</h4>
<p style="color: white">.</p>
<p style="color: white">.</p>
<p style="color: white">.</p>
      <div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" id="imgtest" src="http://www.degreesfinder.com/wp-content/uploads/2012/09/college-student-male.jpg" alt="Test">
    </a>
  </div>
  <div class="media-body">
  </div>
</div>
<h4> “Summer enrichment showed me that my best fit summer program was MITES at MIT and I have never had as much fun during a summer!” - Johnson</h4>
    </div>
    
  </div>
</div> 
</body>
</html>

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :location_type %><br>
    <%= f.text_field :location_type %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :grade_min %><br>
    <%= f.number_field :grade_min %>
  </div>
  <div class="field">
    <%= f.label :grade_max %><br>
    <%= f.number_field :grade_max %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :ethnicity %><br>
    <%= f.text_field :ethnicity %>
  </div>
  <div class="field">
    <%= f.label :begin_date %><br>
    <%= f.date_select :begin_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :travel %><br>
    <%= f.text_field :travel %>
  </div>
  <div class="field">
    <%= f.label :age_min %><br>
    <%= f.number_field :age_min %>
  </div>
  <div class="field">
    <%= f.label :age_max %><br>
    <%= f.number_field :age_max %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12" id="f">
<p id="notice"><%= notice %></p>
<div class = "container"> 
<div class = "row">
<div class = "col-xs-12 col-sm-12 col-md-12" id= "f" >
  


<h1>Programs</h1>

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Name</th>-->
<!--      <th>Description</th>-->
<!--      <th>Link</th>-->
<!--      <th>Price</th>-->
<!--      <th>Location type</th>-->
<!--      <th>City</th>-->
<!--      <th>State</th>-->
<!--      <th>Grade min</th>-->
<!--      <th>Grade max</th>-->
<!--      <th>Subject</th>-->
<!--      <th>Gender</th>-->
<!--      <th>Ethnicity</th>-->
<!--      <th>Begin date</th>-->
<!--      <th>End date</th>-->
<!--      <th>Travel</th>-->
<!--      <th>Age min</th>-->
<!--      <th>Age max</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

  <tbody>
    <% @programs.each do |program| %>
         <a href=<%= program.link %>> <h4><%= program.name %> </h4></a>
      <div class="media">
        <div class="media-left">
            <a href=<%= program.link %>>
              <img class="media-object" src="https://i.ytimg.com/vi/hTeqBLsKdw8/hqdefault.jpg" alt="MIT">
          </a>
          </div>
    <div class="media-body">
      <h4 class="media-heading"></h4>
        <p> Location: <%= program.city %>, <%= program.state %> </p>
        <p> Price: <%= program.price %></p>
        <p> Description: <%= program.description %></p>
        <p> Type of City: <%= program.location_type %></p>
        <p> Dates: <%= program.begin_date %>, <%= program.end_date %> </p>
        <p> Field of Interest: <%= program.subject %> </p>
        <p> Commuter or Residential: <%= program.travel %> </p>
        <p> Grade level Range: <%= program.grade_min %> - <%= program.grade_max %> </p>
        
      </div>
    </div>
      
<!--      <tr>-->
<!--        <td><%= program.name %></td>-->
<!--        <td><%= program.description %></td>-->
<!--        <td><%= program.link %></td>-->
<!--        <td><%= program.price %></td>-->
<!--        <td><%= program.location_type %></td>-->
<!--        <td></td>-->
<!--        <td><%= program.state %></td>-->
<!--        <td><%= program.grade_min %></td>-->
<!--        <td><%= program.grade_max %></td>-->
<!--        <td><%= program.subject %></td>-->
<!--        <td><%= program.gender %></td>-->
<!--        <td><%= program.ethnicity %></td>-->
<!--        <td><%= program.begin_date %></td>-->
<!--        <td><%= program.end_date %></td>-->
<!--        <td><%= program.travel %></td>-->
<!--        <td><%= program.age_min %></td>-->
<!--        <td><%= program.age_max %></td>-->
<!--        <td><%= link_to 'Show', program %></td>-->
<!--        <td><%= link_to 'Edit', edit_program_path(program) %></td>-->
<!--        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <% end %>
<!--  </tbody>-->
<!--</table>-->

<br>

<<<<<<< HEAD
<!--<%= link_to 'New Program', new_program_path %>-->
</div>
</div>
=======
<%= link_to 'New Program', new_program_path %>
</div>
</div> 
>>>>>>> d13bbab5fa36f4785f32c3ce5643c52b79e2dc72
</div>
</body>
</html>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @program.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @program.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @program.link %>
</p>

<p>
  <strong>Price:</strong>
  <%= @program.price %>
</p>

<p>
  <strong>Location type:</strong>
  <%= @program.location_type %>
</p>

<p>
  <strong>City:</strong>
  <%= @program.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @program.state %>
</p>

<p>
  <strong>Grade min:</strong>
  <%= @program.grade_min %>
</p>

<p>
  <strong>Grade max:</strong>
  <%= @program.grade_max %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @program.subject %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @program.gender %>
</p>

<p>
  <strong>Ethnicity:</strong>
  <%= @program.ethnicity %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @program.begin_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @program.end_date %>
</p>

<p>
  <strong>Travel:</strong>
  <%= @program.travel %>
</p>

<p>
  <strong>Age min:</strong>
  <%= @program.age_min %>
</p>

<p>
  <strong>Age max:</strong>
  <%= @program.age_max %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

</body>
</html>

app/views/quizzes/new.html.erb
<div class = "container">
  <div class ="row">
    <div class ="col-xs-12 col-sm-12 col-md-12">
<h1>Summer Program Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>
</div>
</div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>